### PR TITLE
Fix headlines for WhatIf output

### LINKED ISSUE #716: Validate pipeline sets wrong "headline" in comments.
**Describe the bug**

When the validate pipeline posts comments it sets the filename for the resource group as headline.
This may be confusing as it shows the name of a template not actually deployed.

Given a folder containing a template for resource group, `microsoft.resources_resourcegroups-alz-lz1.json`, and adding or changing other templates in the same folder, `SANumber1.bicep`, the feedback still says it comes from the resource group template.

To avoid confusion it should instead show for example the scope as seen right above the actual resources.

**Steps to reproduce**

1. Create a template for a resource group
2. Create a template for another resource
3. run validate pipeline

**Screenshots**

image

### PR DESCRIPTION
**Pull request by bjompen**
# Overview/Summary

This PR changes the headlines of the WhatIf deploys.
If a result is given, the headline will be the scope(s) in which that specific block will change.
If a file has no changes it will output that filename instead.

## This PR fixes/adds/changes/removes

fixes #716 

### Breaking Changes

none

### CODE REVIEW

**Comment by daltondhcp** [comment]
@bjompen - can you please share evidence in the form of a screenshot as well?

**Comment by bjompen** [comment]
Hope this is good enough:

Fixed output:
image
 
 Previous:
 
image

**Comment by bjompen** [comment]
Updated the PR after some discussion to use filename instead, but had to change more files.
The output will now look like this:

image

I have scanned the repo to see if the -Statepath was used anywhere else to avoid broken functions, but it doesn't seem so.
Since the function is internal it should be safe to remove the parameter without it being a breaking change.
Proof in image (shorthand is ok in console 😉)
image

**Review by daltondhcp — APPROVED** [review]
LGTM :octocat:

**Pull request merged**
