### PR TITLE
Add repo dispatch script

### PR DESCRIPTION
**Pull request by matt-FFFFFF**
Adds a PowerShell and *nix shell script to easily send a repo dispatch event to trigger azops-pull

* Infers github repo details from cwd
* Gets creds from ~/.git-credentials if it exists, else can supply using parameters

### CODE REVIEW

**Comment by matt-FFFFFF** [comment]
PowerShell script now added

**Comment by uday31in** [comment]
@matt-FFFFFF  - we have renamed  trigger to make it more explicit. Please update accordingly. 

We also have GH CLI as preferred option, do we need this and want to maintain on long term basis?

**Comment by matt-FFFFFF** [comment]
Personally I think these scripts belong in the Enterprise-Scale repo, that way they are available to customers when they use the template. However I was told to put them here when I raised the original PR on E-S.

Using gh cli is ok, but you need to have it installed, etc. Also, the command is still more complex IMHO.

I really wrote these to make it easier for customers to perform the repo dispatch.

**Comment by daltondhcp** [comment]
@matt-FFFFFF we just added support for the new github actions workflow_dispatch feature with https://github.com/Azure/Enterprise-Scale/pull/60. Does this fulfill the 'easy to trigger' criteria or do you still see that we need to maintain a script in addition to the GH CLI option?

**Comment by matt-FFFFFF** [comment]
The workflow dispatch looks perfect. No need for a script any more :)

Thanks for the great work!

Matt

________________________________

**Comment by daltondhcp** [comment]
Awesome! Thanks!

**Pull request closed without merging**
