### PR TITLE
Expanded Pester automated integration testing

### PR DESCRIPTION
**Pull request by Jefajers**
## Overview/Summary

To increase confidence in changes to the codebase this PR adds additional automated tests to validate three pull operations:

1. Policy assignment at management group scope
2. Role assignment at subscription scope
3. Resource deployment at resource group scope

## This PR fixes/adds/changes/removes

1. Adds deployment of a policy assignment
2. Adds deployment of a role assignment
3. Adds deployment of a resource deployment
4. Adds Pester tests to validate resource discovery
5. Adds logic to remove role assignment at subscription scope for service principal at cleanup
6. Changes the AzOpsPull operation, it performs a discovery which includes roles, policy's and resources to enable the extended tests
7. Fixes spelling output

### Breaking Changes

N/A

## Testing Evidence

Performed a full run of Pester tests resulting in successful deployment and discovery of resources at desired scopes.
Performed a full run of Pester tests resulting in successful deployment and intended failure of resource discovery which the test alerted to for each of the three new scope/types.

## As part of this Pull Request I have

- [x] Checked for duplicate [Pull Requests](https://github.com/Azure/azops/pulls)
- [x] Associated it with relevant [issues](https://github.com/Azure/azops/issues), for tracking and closure.
- [x] Ensured my code/branch is up-to-date with the latest changes in the `main` [branch](https://github.com/Azure/azops/tree/main)
- [x] Performed testing and provided evidence.
- [x] Updated relevant and associated documentation.

### CODE REVIEW

**Review by daltondhcp — APPROVED** [review]
Great work and🩸 💦 😂 ! 
🚢

**Comment by Jefajers** [comment]
YOLO

**Pull request merged**
