### PR TITLE
What-If to output raw Json

### PR DESCRIPTION
**Pull request by Gordonby**
Introduced a new function to output both MD and JSON files

### CODE REVIEW

**Comment by Gordonby** [comment]
@ljtill - used the VSCode dev container route as suggested to test this before PR.

**Review by ljtill — COMMENTED** [review]
Thanks for submitting this PR @Gordonby 👍 

Before merging, please can we update the `Strings.psd1` to include the logging messages for the `Write-PSFMessage` cmdlets.

Path: `src/localized/en-us/Strings.psd1`

**Comment by Gordonby** [comment]
Ok @ljtill - hadn't seen the loc 👍 
done. 🚀

**Review by ljtill — APPROVED** [review]
LGTM

**Pull request merged**
